# Main window settings
WINDOW_NAME: str = "Cryptography"
WINDOW_SIZE: tuple[int] = (1920, 1080)


# Fonts
DEFAULT_FONT_FAMILY: str = "Inter"
DEFAULT_FONT_SIZE: int = 12

# UI components
DIMENSION_UNIT_SIZE: int = 50
ACTION_BUTTON_SIZE: int = 100
BUTTON_DEFAULT_WIDTH: int = DIMENSION_UNIT_SIZE * 3
BUTTON_DEFAULT_HEIGHT: int = DIMENSION_UNIT_SIZE * 1.5
COMBO_BOX_DEFAULT_WIDTH: int = DIMENSION_UNIT_SIZE * 5
LABEL_DEFAULT_SIZE: int = DIMENSION_UNIT_SIZE * 2
MAIN_COMPONENT_DEFAULT_WIDTH: int = DIMENSION_UNIT_SIZE * 12 + LABEL_DEFAULT_SIZE
TEXT_EDIT_DEFAULT_HEIGHT: int = DIMENSION_UNIT_SIZE * 16